### PR TITLE
[Redo] Fix dummy modular format

### LINKED ISSUE #210: `Error while processing route: query reference.orderBy is not a function`
In the dummy app on the query route

### PR DESCRIPTION
**Pull request by charlesfries**
Fixes #210

### CODE REVIEW

File: tests/dummy/app/controllers/query.ts [hunk 1]
```diff
@@ -1,14 +1,20 @@
 import { action } from '@ember/object';
 import Controller from '@ember/controller';
+import {
+  query,
+  orderBy,
+  limit,
+} from 'ember-cloud-firestore-adapter/firebase/firestore';
 
-import firebase from 'firebase/compat/app';
+import type firebase from 'firebase/compat/app';
```
Comment (mikkopaderes) [inline tests/dummy/app/controllers/query.ts:9]: No big deal here, up to you if you want to change it. But I follow Python best practice for import order, which I quote:

> Imports should be grouped in the following order:
>
> Standard library imports.
> Related third party imports.
> Local application/library specific imports.
> You should put a blank line between each group of imports.

Which if I would do would be:

```typescript
import { action } from '@ember/object';
import Controller from '@ember/controller';

import type firebase from 'firebase/compat/app';

import {
  query,
  orderBy,
  limit,
} from 'ember-cloud-firestore-adapter/firebase/firestore';
```

File: tests/dummy/app/routes/query.ts [hunk 2]
```diff
@@ -14,7 +18,7 @@ export default class QueryRoute extends Route {
   public async model(): Promise<ArrayProxy<GroupModel>> {
     return this.store.query('group', {
       filter(reference: firebase.firestore.CollectionReference) {
```
Comment (mikkopaderes) [inline tests/dummy/app/routes/query.ts:20]: The correct type here would now be `CollectionReference` from the modular SDK rather than `firebase.firestore.CollectionReference`.

**Review by mikkopaderes — CHANGES_REQUESTED** [review]

**Review by mikkopaderes — APPROVED** [review]

File: tests/dummy/app/controllers/query.ts (hunk 1 above)
Comment (charlesfries) [reply tests/dummy/app/controllers/query.ts]: Lmk if I didn't do it right, I was unaware of this import organization style but I like it

Comment (mikkopaderes) [reply tests/dummy/app/controllers/query.ts]: I don't want to stress on it too much since it's an opinionated thing, but if you insist, `CollectionReference` is a third party import so it should be in the middle.

```javascript
import { action } from '@ember/object';
import Controller from '@ember/controller';

import { CollectionReference } from 'firebase/firestore';

import {
  query,
  orderBy,
  limit,
} from 'ember-cloud-firestore-adapter/firebase/firestore';
```

Comment (charlesfries) [reply tests/dummy/app/controllers/query.ts]: Ah ok I gotcha now. And no that's totally fine--I love consistency and am very much interested in understanding the patterns you are adhering to so I can follow them
